version: 2
jobs:
  build:
    working_directory: ~/verto
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: webpackcontrib/circleci-node8
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - test:
          name: Test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build