version: 2
jobs:
  build:
    working_directory: ~/verto
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm start test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build